sonar.projectKey=Cazelabs-SAST-Scan
sonar.projectName=Cazelabs-SAST-Scan
sonar.projectVersion=1.0
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.host.url=http://host.docker.internal:9000
sonar. Login=sqp_8b3233bed203230dd770981eb5a6f815435457fc
